**1st June 2026**

**What is NumPy?**
It is a powerful Python library used for 
* Numerical computations
* Working with arrays and matrices
* Mathematical operations
* Data Science and Machine Learning

NumPy: Numerical Python

Advantages of NumPy:
* Faster than Python lists
* Uses less memory
* Supports multi-dimensional arrays
* Large collections of mathematical functions

**List vs Array:**

1. List we can not do element wise operations, but in an array we can.
2. Array to list conversion is possible, and also list to array conversion is possible, but it will lose the dimension.
3. List is heterogenous datatype, but NumPy is a homogeneous data type.

**Suppose your priority order (highest → lowest) is:**

* str
* int
* float
* bool
* NoneType
* other objects

In [1]:
import numpy as np

In [3]:
arr1=np.array(['python',45,91.37,True,18,18+4j])
arr1

array(['python', '45', '91.37', 'True', '18', '(18+4j)'], dtype='<U64')

In [4]:
type(arr1)

numpy.ndarray

In [4]:
arr1.dtype #<U64-> Unicode String

dtype('<U64')

In [5]:
arr1=np.array([45,91.37,True,18,18+4j])
arr1

array([45.  +0.j, 91.37+0.j,  1.  +0.j, 18.  +0.j, 18.  +4.j])

In [6]:
arr2 = np.array([2,3,9,4,7,1])
arr2

array([2, 3, 9, 4, 7, 1])

In [7]:
arr2.ndim #gives the dimension of the data

1

In [9]:
arr2.dtype

dtype('int32')

In [10]:
arr2.size #number of elements in the array

6

In [12]:
arr2.shape #matrix size

(6,)

In [13]:
len(arr2) #same as size

6

In [14]:
arr3=np.array([[10,20],[30,40]])
arr3

array([[10, 20],
       [30, 40]])

In [15]:
arr3.dtype

dtype('int32')

In [16]:
arr3.ndim

2

In [17]:
len(arr3)

2

In [18]:
arr3.size

4

In [19]:
arr3.shape

(2, 2)

In [20]:
arr4=np.array([[0,0,0],[0,0,0],[0,0,0]])
arr4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
z=np.zeros((3,3),dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
x=np.ones((3,4),dtype=int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
a= np.full((3,3),9)
a

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [35]:
k=np.identity(4,dtype=int)
k

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [34]:
n = int(input("give no: "))
a= np.full((3,3),n)
a

give no:  6


array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [36]:
b=np.eye(4,dtype=int)
b

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

**2nd June 2026**

In [8]:
#generating random array values between 1 to 50
arr4= np.random.randint(1,50,12)
arr4

array([46, 41, 47, 12, 42, 36, 44, 48,  3,  1, 46, 47])

In [10]:
np.reshape(arr4,(3,4),order='F')

array([[46, 12, 44,  1],
       [41, 42, 48, 46],
       [47, 36,  3, 47]])

In [11]:
np.reshape(arr4,(4,3),order='F')

array([[46, 42,  3],
       [41, 36,  1],
       [47, 44, 46],
       [12, 48, 47]])

In [12]:
np.reshape(arr4,(6,2),order='F')

array([[46, 44],
       [41, 48],
       [47,  3],
       [12,  1],
       [42, 46],
       [36, 47]])

In [13]:
np.reshape(arr4,(2,6),order='F')

array([[46, 47, 42, 44,  3, 46],
       [41, 12, 36, 48,  1, 47]])

In [16]:
np.reshape(arr4,(12,1))

array([[46],
       [41],
       [47],
       [12],
       [42],
       [36],
       [44],
       [48],
       [ 3],
       [ 1],
       [46],
       [47]])

In [17]:
np.reshape(arr4,(1,12))

array([[46, 41, 47, 12, 42, 36, 44, 48,  3,  1, 46, 47]])

In [33]:
arr6=np.array([[33,31,40,17],[36,21,16,6],[40,2,20,31]])
arr6

array([[33, 31, 40, 17],
       [36, 21, 16,  6],
       [40,  2, 20, 31]])

In [19]:
#Maximum of the matrix
arr6.max()

40

In [26]:
#minimum of the matrix
arr6.min()

2

In [32]:
#Average or mean of the matrix
arr6.mean().round(4)

24.4167

In [28]:
#Total of the matrix
arr6.sum()

293

In [31]:
#variance of the matrix
arr6.var().round(4)

148.2431

In [30]:
#standard deviation of the matrix
arr6.std().round(4)

12.1755

In [33]:
#row wise maximum value
arr6.max(axis=1)

array([40, 36, 40])

In [34]:
#column wise maximum value
arr6.max(axis=0)

array([40, 31, 40, 31])

In [35]:
#gives the position of the maximum value in a row
arr6.argmax(axis=1)

array([2, 0, 0], dtype=int64)

In [36]:
#gives the position of the maximum value in a column
arr6.argmax(axis=0)

array([2, 0, 0, 2], dtype=int64)

In [37]:
arr6[1][2]

16

In [39]:
arr6[1,2]

16

In [40]:
#extract only 1st row values
arr6[0]

array([33, 31, 40, 17])

In [44]:
#extract only 1st column values 
arr6[:,0]

array([33, 36, 40])

In [45]:
#extract only corner elements
arr6[:2,:2]

array([[33, 31],
       [36, 21]])

In [52]:
arr6[1:3,1:3]

array([[21, 16],
       [ 2, 20]])

In [53]:
#extract even index rows and odd index column elements
arr6[::2,1::2]

array([[31, 17],
       [ 2, 31]])

In [54]:
#reverse the matrix
arr6[::-1,::-1]

array([[31, 20,  2, 40],
       [ 6, 16, 21, 36],
       [17, 40, 31, 33]])

In [55]:
#transpose of the matrix
arr6.transpose()

array([[33, 36, 40],
       [31, 21,  2],
       [40, 16, 20],
       [17,  6, 31]])

In [57]:
#extract the elements greater than 20
arr6[arr6>20]

array([33, 31, 40, 36, 21, 40, 31])

In [59]:
#replace the values<0 with 0
arr6[arr6<20]=0
arr6

array([[33, 31, 40,  0],
       [36, 21,  0,  0],
       [40,  0, 20, 31]])

**3rd June 2026**

In [20]:
#create 2*2 two matrix and perform mathematical operations like addition, subtraction, multiplication and divison
arr7=np.array([[10,20],[30,40]])
arr7

array([[10, 20],
       [30, 40]])

In [21]:
arr8=np.array([[1,2],[3,4]])
arr8

array([[1, 2],
       [3, 4]])

In [22]:
arr7+arr8

array([[11, 22],
       [33, 44]])

In [23]:
arr7-arr8

array([[ 9, 18],
       [27, 36]])

In [24]:
arr7*arr8

array([[ 10,  40],
       [ 90, 160]])

In [25]:
arr7/arr8

array([[10., 10.],
       [10., 10.]])

In [26]:
np.matmul(arr7,arr8)

array([[ 70, 100],
       [150, 220]])

In [36]:
#extract odd number elements from matrix
arr6[arr6%2!=0]

array([33, 31, 17, 21, 31])

In [41]:
#extract 2nd maximum value 
smax=np.sort(arr6,axis=None)[-2]
smax

40

In [43]:
sm=np.unique(arr6)[-2]
sm

36

In [44]:
t3m=np.unique(arr6)[-3:]
t3m

array([33, 36, 40])

In [45]:
t3min=np.unique(arr6)[:3]
t3min

array([ 2,  6, 16])

In [46]:
narr=np.array([1,2,2,3,3,4,4,5])
narr

array([1, 2, 2, 3, 3, 4, 4, 5])

In [48]:
#extract duplicate values from array
unique,counts=np.unique(narr,return_counts=True)
print(unique)
print(counts)

[1 2 3 4 5]
[1 2 2 2 1]


In [50]:
unique[counts>1]

array([2, 3, 4])

In [53]:
a=np.array([1,2,3,4,5])
b=np.array([4,5,6,7,8])

In [56]:
#extract common elements from both the arrays
np.intersect1d(a,b)

array([4, 5])

In [57]:
#find elements present in array a but not in array b
np.setdiff1d(a,b)

array([1, 2, 3])

In [58]:
#find elements present in array b but not in array a
np.setdiff1d(b,a)

array([6, 7, 8, 9])

In [59]:
arr=np.array([10,np.nan,20,np.nan])

In [60]:
#replace null value by 0
np.nan_to_num(arr)

array([10.,  0., 20.,  0.])