In [1]:
import numpy as np

In [3]:
arr1=np.array(['python',45,91.37,True,18,18+4j])
arr1

array(['python', '45', '91.37', 'True', '18', '(18+4j)'], dtype='<U64')

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.dtype #<64 -> Unicode String

dtype('<U64')

In [6]:
arr2 = np.array([2,3,9,4,7,1])
arr2

array([2, 3, 9, 4, 7, 1])

In [7]:
arr2.ndim

1

In [9]:
arr2.dtype

dtype('int32')

In [10]:
arr2.size

6

In [12]:
arr2.shape

(6,)

In [13]:
len(arr2)

6

In [14]:
arr3=np.array([[10,20],[30,40]])
arr3

array([[10, 20],
       [30, 40]])

In [15]:
arr3.dtype

dtype('int32')

In [16]:
arr3.ndim

2

In [17]:
len(arr3)

2

In [18]:
arr3.size

4

In [19]:
arr3.shape

(2, 2)

In [20]:
arr4=np.array([[0,0,0],[0,0,0],[0,0,0]])
arr4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
z=np.zeros((3,3),dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [23]:
x=np.ones((3,4),dtype=int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
a= np.full((3,3),9)
a

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [35]:
k=np.identity(4,dtype=int)
k

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [34]:
n = int(input("give no: "))
a= np.full((3,3),n)
a

give no:  6


array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [36]:
b=np.eye(4,dtype=int)
b

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])